[Hypr-Chroma]
description = "Apply Chromakey algorithm"
authors = ["alexhulbert"]
output = "out/hyprchroma.so"
build = [
    "make all",
]
commit_pins = [
    # v Hyprland                                  v hyprchroma
    ["fe7b748eb668136dd0558b7c8279bfcd7ab4d759", "2629145e163f16b525bd5a3f310837e146c38e9f"], # v0.39.1
]
