name: Hyprland Breaking Change Notifier

on:
  schedule:
  - cron: "0 6 * * *"
  workflow_dispatch: {}

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Nix
        uses: cachix/install-nix-action@v26

      - name: Compile
        run: nix build
