name: Hyprland Breaking Change Notifier

on:
  schedule:
  - cron: "0 6 * * *"
  workflow_dispatch: {}

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: m0rf30/arch-yay

    steps:
      - name: Hyprland
        run: yay -Syu --noconfirm hyprland-git
        
      - uses: actions/checkout@v3
      - name: Compile
        run: make all
