name: Hyprland Breaking Change Notifier

on:
  schedule:
  - cron: "0 6 * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Get Hyprland
      run: make setup-headers VERSION=HEAD
    - name: Compile
      run: make build-version VERSION=HEAD
