name: Hyprland Breaking Change Notifier

on:
  schedule:
  - cron: "0 6 * * *"
  workflow_dispatch: {}

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: nixos/nix

    steps:
      - uses: actions/checkout@v3

      - name: Compile
        run: nix --extra-experimental-features nix-command --extra-experimental-features flakes build

